name: Lint
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
  pull_request:
    branches:
      - master
    paths:
      - "**.py"

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: black lint check
        uses: lgeiger/black-action@master
        with:
          args: '--check .'
