name: Test
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
  pull_request:
    branches:
      - master
    paths:
      - "**.py"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python3.9 -m pip install -r dev.requirements.txt
      - name: Run unit tests
        run: python -m pytest -vv tests/unit
      - name: Run system tests
        run: python -m pytest -vv tests/system
