name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python3.9 -m pip install -r dev.requirements.txt
      - name: Run unit tests
        run: python -m pytest -vv tests/unit/
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python3.9 -m pip install -r dev.requirements.txt
      - name: Run integration tests
        run: python -m pytest -vv tests/integration/
  system-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python3.9 -m pip install -r dev.requirements.txt
      - name: Run system tests
        run: python -m pytest -vv tests/system/
  coverage:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, system-tests]
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python3.9 -m pip install -r dev.requirements.txt
      - name: Run tests with coverage
        run: python -m pytest --cov=./ --cov-report=xml -vv tests/
      - name: Publish coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
  packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python3.9 -m pip install -r dev.requirements.txt
      - name: Create package
        run: ./tools/package.sh
