name: Test release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python3.9 -m pip install -r dev.requirements.txt
      - name: Release (dry run)
        run: tools/release.sh --release-mode test --pypi-key ${{ secrets.QUICKFOREX_TEST_PYPI }}
